config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }, 
                   path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  #get 'home/index'
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'inicio', to: 'home#inicio', as: 'inicio'
  # get '/libros/:libro_id/resenas', to: 'resenas#index'
  # get 'resenas/:libro_id', to: 'resenas#new'

  # resources :resenas
  # resources :libros
  get '/profile', to: 'users#show'

  resources :libros do
    resources :resenas
  end
  resources :libros do
    resources :mensajes
  end
  resources :libros do
    resources :compras
  end
  resources :user do
    resources :compras
  end
end

app/models/compra.rb
class Compra < ApplicationRecord
  validates :estado, presence: true
  belongs_to :user
  belongs_to :libro
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
# GET /compras
    def index
        @user = current_user
        @compras = @user.compras
    end
# GET /compras/1
    def show
        @user = current_user
        @compra = @user.compras.find(params[:id])
    end
# GET /compras/new
    def new
        @libro = Libro.find(params[:libro_id])
        @user = current_user
        @compra = @user.compras.new
    end
# POST /compras
    def create
        @libro = Libro.find(params[:libro_id])
        @user = current_user
        @compra = @user.compras.new(estado: "E")
        @compra.libro = @libro
        if @compra.save
            redirect_to user_compras_path(current_user.id), notice: "La compra se ha creado correctamente."
        else
            render :new, status: :unprocessable_entity
        end
    end
# GET /compras/1/edit
    def edit
        @user = current_user
        @compra = @user.compras.find(params[:id])
    end
# PATCH /compras/1
    def update
        @user = current_user
        @compra = @user.compras.find(params[:id])
        if @compra.update(compra_params)
            redirect_to :user_compras, notice: "La compra se ha actualizado correctamente."
        else
            render :edit, status: :unprocessable_entity
        end
    end
# DELETE /compras/1
    def destroy
        @user = current_user
        @compra = @user.compras.find(params[:id])
        @compra.destroy
        redirect_to :user_compras, notice: "La compra se ha eliminado correctamente."
    end
# Agregar al final de la clase por el control de accesos
    private
        def compra_params
            params.require(:compra).permit(:estado)
    end
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/views/compras/edit.html.erb
<html>
<head>
    <%= stylesheet_link_tag 'libros' %>
</head>

<body>
<div class="page-container">
<div class ="content-wrap">

<%= render 'componentes/header' %>

<h1>Editar una compra de <%= @compra.user.nombre %></h1>
<%= form_for([@user, @compra]) do |form| %>
  <div class="field">
    <%= form.label :estado %><br />
    <%= form.select :estado, options_for_select([['En revisión', 'E'], ['Aceptado', 'A'], ['Rechazado', 'R']], selected: @compra.estado), include_blank: false %>
  </div>
  <%= form.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>

</div>
<%= render 'componentes/footer' %>
</div>
</body>

</html>

app/views/compras/index.html.erb
<h1>Compras de <%= @user.nombre %></h1>
<table>
  <thead>
    <tr>
      <th>Libro</th>
      <th>Estado</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @compras.each do |compra| %>
      <tr>
        <td><%= compra.libro.titulo %></td>
        <td>
          <% if compra.estado == "E" %>
            <p>En Revisión</p>
          <% elsif compra.estado == "A" %>
            <p>Aprobado</p>
          <% elsif compra.estado == "R" %>
            <p>Rechazado</p>
        <% end %>
        </td>
        <td><%= link_to "Mostrar", user_compra_path(@user, compra) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/compras/new.html.erb
<h1>Nueva compra</h1>

<%= form_for([@libro, @compra]) do |form| %>
  <%= form.hidden_field :libro_id, value: @libro.id %>
  <p>Libro:<span><%= @libro.titulo %></span></p>
  <p>Precio:<span><%= @libro.precio %></span></p>
  <%= form.submit "Confirmar compra" %>
<% end %>

app/views/compras/show.html.erb
<h1>Compra #<%= @compra.id %></h1>

<p><strong>Estado:</strong> <%= @compra.estado %></p>
<p><strong>Libro:</strong> <%= @compra.libro.titulo %></p>
<p><strong>Usuario:</strong> <%= @compra.user.nombre %></p>
<p><strong>Fecha de compra:</strong> <%= @compra.created_at.strftime("%d/%m/%Y") %></p>

<%= link_to "Editar", edit_user_compra_path(@user, @compra) %>
<!--
<%= link_to "Eliminar", user_compra_path(@user, @compra), method: :delete, data: { confirm: "¿Estás seguro de que quieres eliminar esta compra?" } %>
-->
<%= link_to "Destroy", :user_compra,
        data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
        } %>